### ISSUE TITLE
Fresh install issues

### ISSUE THREAD

**Issue by RobSisson** [hotwire-django/turbo-django#74]
Hi Everyone! 

Been figuring out if I should go with Hotwire or htmx/alpine and wanted to get something running to then explore how things work as I'm pretty new to coding so abstractions are a bit tricky.

Followed the instructions to get the chat experiment running and it runs, and unfortunately I've run into a ValueError:
`[18/Nov/2022 18:53:13] "GET /ws/ HTTP/1.1" 500 131700
Internal Server Error: /ws/
Traceback (most recent call last):
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'ws'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\detail.py", line 106, in get
    self.object = self.get_object()
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\detail.py", line 36, in get_object
    queryset = queryset.filter(pk=pk)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1216, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'ws'.
[18/Nov/2022 18:53:24] "GET /ws/ HTTP/1.1" 500 131700
Internal Server Error: /ws/
Traceback (most recent call last):
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'ws'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\detail.py", line 106, in get
    self.object = self.get_object()
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\views\generic\detail.py", line 36, in get_object
    queryset = queryset.filter(pk=pk)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1416, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1435, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1370, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\sql\query.py", line 1216, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Users\rob_s\PycharmProjects\Autobiography\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'ws'.
[18/Nov/2022 18:53:35] "GET /ws/ HTTP/1.1" 500 131700
`

I've tried searching the code base for ws to see where it was coming from but no luck, any pointers with this?

Also, I'm not sure if this is related to this issue, or if I haven't understood what the demo was supposed to show, but when I submit a new message in the chat, it requires a full page reload. 

My (perhaps mis)understanding was that turbo enables real time DOM manipulation without reloading, is this correct or have I got the wrong idea?

**Comment by scuml** [comment]
> My (perhaps mis)understanding was that turbo enables real time DOM manipulation without reloading, is this correct or have I got the wrong idea?

No - this is the correct understanding.  On my todo list is to find a place to host the example pages so people can see the expected behavior without figuring out how to run things locally. 

The `/ws/` is the websocket path this library uses for pushing results to the front-end.  I can't figure out from the error what configuration needs to be adjusted to get that working. 

My recommendation if you are just getting started with Turbo is to initially not use this library, but instead include the Turbo library in a template to get a feel for how the basic functionality works.

In a base template, in your `<head>` tag, add `<script src="https://unpkg.com/@hotwired/turbo@7.2.4/dist/turbo.es2017-umd.js"></script>`.  Now start clicking around your test site and notice how fast things work due to the page not fully reloading.

**Comment by RobSisson** [comment]
Perfect, maybe I haven't got websocket set up correctly, will look into it
further,

Will do, thanks!

**Comment by RobSisson** [comment]
Hi again scuml,

I took your advice, and love the results of popping in the script tag - it's wayy faster! Actually blows my mind tbh, such awesome work; and an unreal tip! Much appreciated!

Apologies in advance for being an absolute askhole; there's a more than q few questions below,

As a result of dipping my toe in here, I'd really like to get the full system up and running with the rest of my site, fully integrating it meaning that htmx is no longer required and moving into ios and android is a smoother process in the long run. 

Firstly, is it recommended to go the full hog? or should I wait for a stable build as its still in development? Also, not sure about how things are progressing as their seems to have be slight delays to Strada, but the turbo package seems to be semi active still with updates every two months or so

I've had a toy around and got the reminders example app working as expected and seems fab, however the same /ws/ error is still present, but this time its a 404 rather than 500, and there's no extra details other than a broken pipe.

'[22/Nov/2022 08:24:12] "GET /ws/ HTTP/1.1" 404 2377
Not Found: /ws/
[22/Nov/2022 08:24:21] "GET /ws/ HTTP/1.1" 404 2377
Not Found: /ws/
[22/Nov/2022 08:24:31] "GET /ws/ HTTP/1.1" 404 2377
Not Found: /ws/
[22/Nov/2022 08:24:42] "GET /ws/ HTTP/1.1" 404 2377
Not Found: /ws/
[22/Nov/2022 08:24:53] "GET /ws/ HTTP/1.1" 404 2377
Not Found: /ws/
[22/Nov/2022 08:25:04] "GET /ws/ HTTP/1.1" 404 2377
[22/Nov/2022 08:25:04,317] - Broken pipe from ('127.0.0.1', 63544)
Not Found: /ws/
[22/Nov/2022 08:25:15] "GET /ws/ HTTP/1.1" 404 2377

`

I was thinking it'd be a nice way to get familiar with django-turbo for me to try and figure out whats going on with the /ws/ issue, but I'm not exactly sure where to start, any recommendations?

As far as I know, I just followed the install instructions of cloning the repo, setting up the venv, migrating, creating a super user, and running the server, without tweaking anything. 

Following this, I've also tried having an ubuntu VM (I'm on windows) with a Redis server open and running alongside the django server, and putting the following in the Channel Layers as recommended in other areas of the docs:

`CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}`

However the app still pulls the /ws/ and broken pipe bug regardless. I found some details about the broken pipe being [a bug which can be ignored](https://code.djangoproject.com/ticket/4444), but still not sure on the /ws/

I've tried stackoverflowing it, but with no luck; only recommendations such as having something else open on the port - which I don't have, or changing regex expressions (but I can't even find where the /ws/ url is coming from as I've tried searching for it in the entire package and nothing came up) were there.

One thing which makes me a curious is the change of the 500 error to the 404, in the two apps - not sure exactly how web sockets work though so although this seems to be a lead to explore, I'm not sure where to start. Should I just study the websockets documentation further, or is there anything else you'd recommend?

Also, as I'm intending to convert from HTMX to Turbo, are there any documents which could help with that process? I was thinking of trying to effectively do the opposite of the Turbo to HTMX docs [here ](https://htmx.org/migration-guide-hotwire-turbo/), however any advice would be massively appreciated.

Thanks in advance - and for reading all of this - don't blame you if you didnt though!

All the best,
Rob

**Comment by scuml** [comment]
The Turbo and Stimulus components of Hotwire are production ready.  Basecamp relies on them as the foundation of their email solution [Hey](https://www.hey.com/). I recommend diving right in and joining the community.  It is a fast and fun way to develop web apps, and other solutions feel weighty and cumbersome next to it.

If you are diving in more, I'd recommend implementing a simple form next:
  * Create a page that houses a form, but put the form in a subview that only returns the form.
  * Load the form on the page with:

```
# Place on page housing the form
<turbo-frame id="purchase_form" src="{% url 'form_view_name' %}"></turbo-frame>

# views.py
def form_view_name(request):
    if request.method == "POST":
        form = PurchaseForm(request.POST)

        if form.is_valid():
            # pass state
            return redirect('checkout')
    else:
        form = PurchaseForm()

    return render(request, 'purchase_form.html', {
        "form": form,
    }, status=form.errors and 422 or 200)


# purchase_form.html
<turbo-frame id="purchase_form">
    <form action="{% url 'form_view_name' %}" method="POST">
        {{form.as_p}}
    </form>
</turbo-frame>
```

Then I'd identify if you need to push data to the user - in which case you'l need to set up Turbo Streams.  I'll try to find time to rewalk through the setup myself to see if I can replicate this problem.  If you want to try to do a screen share at some point, that might be the easiest way to debug.  Let me know if you'd be interested in that.

**Comment by RobSisson** [comment]
Perfect, I'll spend some time going through the stuff over the next few days as advised, and see how far I can get on my own before taking your time - though your offer is massively appreciated and I've no doubt when I'm a bit more informed on the topic you'd be able to answer the properly formed questions I encounter.

Thanks for your support with this, it's been phenomenal 🙏

Totally agree about the comments relating to the troublesome nature of other systems, even htmx felt like a breath of fresh air compared to the convoluted set up required to get simple crud functionality working with ajax, not to mention trying to reuse the same basic code in different instances.

From what I can see, turbo frames operates similarly to  https://github.com/EmilStenstrom/django-components, which I was thinking of using with HTMX and Alpine.js to overcome the reusablity issue, however frames seems to have significantly easier implementation.

As I mentioned over the next few days I will try to get something simple sorted and record a loom screen capture of the ws error I'm encountering with the examples.

Once again, thank you!

**Comment by RobSisson** [comment]
Hi @scuml - I solve the /ws/ bug! 

I added 'daphne' as an installed app and had a redis server running alongside and it works like a charm!

Not sure if this is related to the fact I'm using pycharm and so already have a venv built, but I expect its not?

Thinking of creating a pull request to update the settings to include it and improving the documentation a little to make turbo-django more accessible to new comers - it's my first one!
